### ISSUE TITLE
XMLHttpRequest is not supported

### ISSUE THREAD

**Issue by dortamiguel** [thaliproject/jxcore-cordova#5]
Hi, I found that the XMLHttpRequest is not working in the jxcore-cordova plugin, if you put the following code as a normal script loaded from the **index.html** everything is fine but if I do it inside the **jxcore/app.js** it fails.

``` javascript
var XMLHttpFactories = [
    function () {return new XMLHttpRequest()},
    function () {return new ActiveXObject("Msxml2.XMLHTTP")},
    function () {return new ActiveXObject("Msxml3.XMLHTTP")},
    function () {return new ActiveXObject("Microsoft.XMLHTTP")}
];

var xhr = null;
for (var i=0;i<XMLHttpFactories.length;i++) {
    try { xhr = XMLHttpFactories[i](); }
    catch (e) { continue; }
    break;
}
console.log(xhr);
if (!xhr) throw console.log("XMLHttpRequest is not supported");
```

I have the **Content-Security-Policy** on my **index.html** but I don't know where to put it inside the **jxcore/app.js**.

**Comment by yaronyg** [comment]
First, I apologize @ellipticaldoor. We are using huboard to manage our issues and it has a really annoying behavior that it puts new bugs into our 'icebox' where we ignore them. I am actively talking to Huboard about fixing this so that we see new issues from the community front and center. I apologize for the delay in responding.

Second, this bug really shouldn't be filed here, it should be filed on https://github.com/jxcore/jxcore-cordova. That is the real home of jxcore-cordova. This is just a fork.

Third, XMLHttpRequest is a browser feature. But JXcore is node. You wouldn't use XMLHttpRequest. You would use Node's built in HTTP client support (and more likely the npm request library).
